## Learning Objective



At the end of this experiment, you will be able to :

* Use Pandas Library

## Setup Steps

## Exercise 1

### a) Import pandas and check for the version

In [1]:
# Your Code Here
import pandas as pd

### b) We have some made-up data for this exercise. It is in the form of a dictionary. The field *area* has to be used as the index. Create a Dataframe using the data.

In [3]:
data = {'Capitals': ['PANAJI', 'CHANDIGARH', 'PATNA', 'AGARTALA'],

      'Population': ['1,347,668', '21,144,564', '82,998,509','3,199,203'],
 
      'States': ['GOA', 'HARYANA', 'BIHAR', 'TRIPURA'],
 
      'Visitors': [300, 4000, 50, 80000],

      'area' : ["3,702", "44,212" ,"94,163", "10,486"]}

You can refer the below link to know about the syntax to create a dataframe 


https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html

In [5]:
# Your Code Here

df=pd.DataFrame(data=data)
print(df)

     Capitals  Population   States  Visitors    area
0      PANAJI   1,347,668      GOA       300   3,702
1  CHANDIGARH  21,144,564  HARYANA      4000  44,212
2       PATNA  82,998,509    BIHAR        50  94,163
3    AGARTALA   3,199,203  TRIPURA     80000  10,486

### c) Display only Capitals and States columns from the dataframe

In [9]:
# Your Code Here
print(df[['Capitals','States']])

     Capitals   States
0      PANAJI      GOA
1  CHANDIGARH  HARYANA
2       PATNA    BIHAR
3    AGARTALA  TRIPURA

### d) What is the total number of visitors?

In [12]:
# Your Code Here
print(df['Visitors'].sum())

84350

### e) In the row with the index value "44,212" change the count of visitors to 5500

In [23]:
 df.loc[(df.area == '44,212'),'Visitors'] = '5500'

 print(df)

     Capitals  Population   States Visitors    area
0      PANAJI   1,347,668      GOA      300   3,702
1  CHANDIGARH  21,144,564  HARYANA     5500  44,212
2       PATNA  82,998,509    BIHAR       50  94,163
3    AGARTALA   3,199,203  TRIPURA    80000  10,486

### Summary

To know more about Pandas, you can refer below link :

https://www.machinelearningplus.com/python/101-pandas-exercises-python/